WORKERS_CHANNEL = "workchannel"
CHANNEL_TO_END = "endchannel"

GET_FULL_GAME_STATE = '{"action" : "queue_end"}'
CLIENT_CONNECTED_STR = "connected"
CLIENT_CONNECTED = '{"action" : "' + CLIENT_CONNECTED_STR + '"}'
CLIENT_DISCONNECTED_STR = "disconnected"
CLIENT_DISCONNECTED = '{"action" : "' + CLIENT_DISCONNECTED_STR + '"}'

CLIENT_POSITIONING = {
    "CLIENT_DEFAULT_X": 0.45,
    "CLIENT_DEFAULT_Y": 0.12
}
GAME_CONSTANTS = {
    "MAX_PLAYERS_IN_ROOM": 6
}